### ISSUE TITLE
TypeError: mitt is not a function

### ISSUE THREAD

**Issue by SergiusSidorov** [lgraubner/sitemap-generator#21]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Error: TypeError: mitt is not a function

**If the current behavior is a bug, please provide the steps to reproduce.**

```
export const sitemap = (host: string) => new Promise<string>((resolve, reject) => {
  var generator = SitemapGenerator(host, {
    crawlerMaxDepth: 3,
    stripQuerystring: false
  });

  generator.on('done', (stats) => {
    console.log(`sitemap generation finished: ${stats}`);
    return resolve(stats);
  });

  generator.on('error', (err) => {
    console.log(`sitemap generator error: ${err}`);
    return reject(err);
  });

  generator.on('ignore', (url) => {
    console.log(`sitemap generator will ignore url: ${url}`); 
  });

  console.log(`sitemap generator crawler starting on ${host}`);
  generator.start();
});

sitemap("localhost:4000")
        .then(a => console.log('ok'))
        .catch(err => console.log(`error: ${err}`));
```

**What is the expected behavior?**
Generated sitemap.xml

**Comment by lgraubner** [comment]
Hi! I cannot reproduce your problem. Are you sure all dependencies are installed correctly? `mitt` is a dependency of `sitemap-generator`.
Are you trying to use this package in the browser (export is more common for browser development ;))? This package is meant to be used only with Node.js.

**Comment by raza2022** [comment]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
should be working as expected with Angular server side rendering

**If the current behavior is a bug, please provide the steps to reproduce.**
I am not sure it's a bug or am missing something from documentation.
Steps to reproduce :-
Download the [finished sample code](https://next.angular.io/generated/zips/universal/universal.zip) from the [Universal Guide](https://next.angular.io/guide/universal).
Unzipped and installed dependencies (with `npm install`).
Enabled SW with `ng add @angular/pwa --project=angular.io-example`.
Built with `npm run build:ssr`.
Run with `npm run serve:ssr`.

then just added your sitemap-generator sample integration code in `server.ts`
now build with `npm run build:ssr`
Run with `npm run serve:ssr`

**What is the expected behavior?**
TypeError: mitt is not a function

**Comment by lgraubner** [comment]
I don't think you are using it right. You should run the sitemap-generator _after_ you created your site generating SSR stuff etc. This is a crawler and not intended to use during a build process.

**Comment by lgraubner** [comment]
It doesn't matter what you use for your stack. The important thing is, that you use SSR, what you are obviously doing. Deploy your app as you would normally and create the sitemap afterwards. Simplest way would be to use the [CLI](https://github.com/lgraubner/sitemap-generator-cli).

**Comment by lgraubner** [comment]
Answered here: lgraubner/sitemap-generator-cli#32
